спринт 14 / вторая версия
eklerkjke/java-shareit pull request #2
Opened 2024-12-29 08:04 UTC by eklerkjke

спринт 14 / первая версия

2024-12-30 01:25 UTC, afomkina requested changes
Получилась отличная работа 👍

2024-12-30 01:25 UTC, afomkina commented on src/main/java/ru/practicum/shareit/exception/EmailDuplicationException.java
> +@ResponseStatus(HttpStatus.CONFLICT) // Устанавливаем статус 409 (конфликт) для этого исключения
Эту аннотацию можно убрать, так как она объявлена в обработчике ошибок

2024-12-30 01:25 UTC, afomkina commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ErrorResponse handleMethodArgumentNotValidException(final MethodArgumentNotValidException e) {
Нужно переименовать все однобуквенные переменные

2024-12-30 01:25 UTC, afomkina commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +    public ErrorResponse(String error) {
Конструктор можно тоже сгенерировать с помощью `@AllArgConstructor`

2024-12-30 01:25 UTC, afomkina commented on src/main/java/ru/practicum/shareit/exception/NotFoundException.java
> +@ResponseStatus(HttpStatus.NOT_FOUND) // Устанавливаем статус 404 (Не найдено) для этого исключения
Нужно удалить

2024-12-30 01:25 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto createItem(@RequestHeader(name = "X-Sharer-User-Id") Long ownerId, @Valid @RequestBody ItemDto item) {
Нужно вынести повторяющийся хэдер в отдельный класс и сделать его публичной константой, чтобы избежать дублирований в других классах. Чтобы быстро поправить все значения, можно воспользоваться горячими клавишами в IDEA: [Ctrl+Shift+R](https://www.jetbrains.com/help/idea/finding-and-replacing-text-in-project.html?keymap=primary_windows#replace_search_string_in_project)

2024-12-30 14:38 UTC, eklerkjke commented on src/main/java/ru/practicum/shareit/exception/EmailDuplicationException.java
> +@ResponseStatus(HttpStatus.CONFLICT) // Устанавливаем статус 409 (конфликт) для этого исключения
поправил

2024-12-30 14:38 UTC, eklerkjke commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +    public ErrorResponse(String error) {
поправил

2024-12-30 14:38 UTC, eklerkjke commented on src/main/java/ru/practicum/shareit/exception/NotFoundException.java
> +@ResponseStatus(HttpStatus.NOT_FOUND) // Устанавливаем статус 404 (Не найдено) для этого исключения
поправил

2024-12-30 14:38 UTC, eklerkjke commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto createItem(@RequestHeader(name = "X-Sharer-User-Id") Long ownerId, @Valid @RequestBody ItemDto item) {
поправил

2024-12-31 01:01 UTC, afomkina approved these changes

2025-01-04 07:55 UTC, merged